// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDnjnPF_MvFSW6W_zBQYLDj-c850k_afR4',
    appId: '1:877730540624:web:dfd55a3b15ea02f6db3555',
    messagingSenderId: '877730540624',
    projectId: 'flemoo-aa360',
    authDomain: 'flemoo-aa360.firebaseapp.com',
    storageBucket: 'flemoo-aa360.appspot.com',
    measurementId: 'G-0QJFNXRVSR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5b-mhOuLlprswHbvFOn7UgkI0wASgCpA',
    appId: '1:877730540624:android:f7eb36d0f6d7999adb3555',
    messagingSenderId: '877730540624',
    projectId: 'flemoo-aa360',
    storageBucket: 'flemoo-aa360.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDmc7gOlNtRokDyFUfTmBluIYdumfY2Fqw',
    appId: '1:877730540624:ios:fe75454ed084ad7cdb3555',
    messagingSenderId: '877730540624',
    projectId: 'flemoo-aa360',
    storageBucket: 'flemoo-aa360.appspot.com',
    iosBundleId: 'com.example.flemooApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDmc7gOlNtRokDyFUfTmBluIYdumfY2Fqw',
    appId: '1:877730540624:ios:fe75454ed084ad7cdb3555',
    messagingSenderId: '877730540624',
    projectId: 'flemoo-aa360',
    storageBucket: 'flemoo-aa360.appspot.com',
    iosBundleId: 'com.example.flemooApp',
  );
}
